import { useState } from 'react'
import { FileText, Download, Plus, Clock, X, Sparkles, CheckCircle, BarChart2 } from 'lucide-react'
import { mockReports } from '@/api/mock/data'

const typeColor = (t: string) =>
  t === 'executive' ? 'primary' : t === 'board' ? 'ai' : t === 'weekly' ? 'teal' : 'muted'

const typeLabel = (t: string) =>
  ({ executive: 'Executive', weekly: 'Weekly Review', board: 'Board Report', customer: 'Customer Health' })[t] ?? t

// ── Report content expanded view ─────────────────────────────────────────────
const FULL_CONTENT: Record<string, { sections: { title: string; body: string }[] }> = {
  '1': {
    sections: [
      { title: 'Revenue Performance', body: 'Monthly revenue reached ₹2.41 Crore, up 8.3% vs last month. Enterprise segment grew 8.7% MoM. SMB declined 7.3% — requires attention. ARR stands at ₹28.99 Crore (+12.4% YoY).' },
      { title: 'Customer Health', body: '34 enterprise accounts in the West region show health scores below 65. Churn risk: ₹3.57 Crore ARR. Net Promoter Score improved to 67 (+3pts vs last quarter). Total customers: 412.' },
      { title: 'Pipeline & Forecast', body: 'Sales pipeline at ₹10.71 Crore (3.2x Q3 target coverage). 3 mid-market deals totaling ₹66.3L in final stage. 90-day revenue forecast: ₹79.05 Crore (+81% model confidence).' },
      { title: 'Key Risks', body: 'Enterprise churn in West region (₹3.57Cr at risk), paid search conversion decline (₹15.3L/month impact), Salesforce data sync failure (pipeline data stale for 6 hours).' },
      { title: 'Recommended Actions', body: '1. Launch enterprise renewal outreach (West region, 7-day window). 2. Restore paid search budget for Brand + Competitor campaigns. 3. Re-sync Salesforce connector.' },
    ],
  },
  '2': {
    sections: [
      { title: 'Deal Velocity', body: 'Deal velocity improved 12% week-over-week. 8 new deals entered the pipeline. Average deal size: ₹24.14 Lakhs. Win rate stable at 38%.' },
      { title: 'Support & Operations', body: 'Support ticket volume up 38% — Feature X documentation gap identified. Average resolution time: 4.2 days. Action: UX improvements and documentation update planned for Aug 15.' },
      { title: 'Weekly Highlights', body: 'Q3 pipeline target on track at ₹10.71Cr. NPS survey closed: 67 (highest since Q3 2025). Google Analytics 4 integration completed with 6 months historical data.' },
    ],
  },
  '3': {
    sections: [
      { title: 'Q2 Financial Summary', body: 'Q2 revenue: ₹66.3 Crore (94% of target). ARR grew 28% YoY to ₹28.99 Crore. Gross margin expanded to 78%. Operating cash flow positive for 4th consecutive quarter.' },
      { title: 'Customer Metrics', body: 'Customer count: 412 (+18% YoY). Churn rate: 2.1% (best since Q1 2024). NPS: 67 (+9pts YoY). Enterprise accounts now represent 57% of ARR.' },
      { title: 'Strategic Highlights', body: 'Mid-market expansion strategy delivering results. 3 new enterprise logos signed in Q2. Product NPS improved following v4.2 release. Two strategic partnerships signed.' },
    ],
  },
  '4': {
    sections: [
      { title: 'NPS & Satisfaction', body: 'NPS improved to 67, best score since Q3 2025. Promoters: 48%, Passives: 30%, Detractors: 22%. Response rate: 24% (below target — domain deliverability issue identified).' },
      { title: 'Churn Analysis', body: 'Churn rate: 2.1% (−0.4pp MoM). 34 accounts flagged for proactive outreach. Combined ARR at risk: ₹3.57 Crore. West region CSM coverage gap identified as primary risk factor.' },
      { title: 'Health Score Distribution', body: 'Healthy (>80): 52% of accounts. At Risk (60–80): 35%. Critical (<60): 13% (primarily West region enterprise). Immediate outreach recommended for critical segment.' },
    ],
  },
}

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a'); a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

function buildPDFText(report: (typeof mockReports)[0]): string {
  const content = FULL_CONTENT[report.id]
  const sections = content?.sections ?? []
  const lines = [
    `BUSINESS INTELLIGENCE REPORT`,
    `================================`,
    `Title: ${report.title}`,
    `Type: ${typeLabel(report.type)}`,
    `Date: ${report.date}`,
    `Generated by: InsightIQ AI`,
    ``,
    ...sections.flatMap((s) => [`${s.title.toUpperCase()}`, `${'-'.repeat(s.title.length)}`, s.body, ``]),
    `[End of Report]`,
  ]
  return lines.join('\n')
}

function buildCSV(report: (typeof mockReports)[0]): string {
  const content = FULL_CONTENT[report.id]
  const rows = [['Section', 'Content'], ...(content?.sections ?? []).map((s) => [s.title, `"${s.body.replace(/"/g, '""')}"`])]
  return rows.map((r) => r.join(',')).join('\n')
}

export default function Reports() {
  const [reports, setReports] = useState(mockReports)
  const [viewing, setViewing] = useState<string | null>(null)
  const [generating, setGenerating] = useState(false)
  const [generated, setGenerated] = useState(false)

  const viewingReport = reports.find((r) => r.id === viewing)

  function handleGenerate() {
    setGenerating(true)
    setGenerated(false)
    setTimeout(() => {
      setGenerating(false)
      setGenerated(true)
      setReports((prev) => [
        {
          id: String(Date.now()),
          title: `AI Report — ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}`,
          type: 'executive',
          date: new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
          status: 'ready',
          preview: 'AI-generated executive summary based on the latest data across all connected sources. Revenue, churn, pipeline, and operational metrics included.',
        },
        ...prev,
      ])
      setTimeout(() => setGenerated(false), 3000)
    }, 2000)
  }

  return (
    <div className="page-enter">
      <div className="analytics-header">
        <div>
          <h1 className="page-title">Reports</h1>
          <p className="page-subtitle">AI-generated executive reports and scheduled deliveries</p>
        </div>
        <button
          className="btn btn--primary btn--sm"
          onClick={handleGenerate}
          disabled={generating}
          style={{ gap: 6 }}
        >
          {generating
            ? <><Sparkles size={13} style={{ animation: 'spin 1s linear infinite' }} /> Generating…</>
            : generated
              ? <><CheckCircle size={13} style={{ color: '#fff' }} /> Generated!</>
              : <><Plus size={13} /> Generate Report</>
          }
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: 16 }}>
        {reports.map((report) => (
          <div key={report.id} className="card" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div style={{ width: 40, height: 40, background: 'var(--color-surface-muted)', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <FileText size={18} style={{ color: 'var(--color-primary)' }} />
              </div>
              <span className={`badge badge--${typeColor(report.type)}`}>{typeLabel(report.type)}</span>
            </div>

            <div>
              <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 4 }}>{report.title}</div>
              <div style={{ fontSize: 12, color: 'var(--color-text-muted)', display: 'flex', alignItems: 'center', gap: 6 }}>
                <Clock size={11} /> {report.date}
              </div>
            </div>

            <div style={{ fontSize: 12, color: 'var(--color-text-secondary)', lineHeight: 1.6, padding: '10px 12px', background: 'var(--color-surface-muted)', borderRadius: 6 }}>
              {report.preview}
            </div>

            <div style={{ display: 'flex', gap: 6, marginTop: 'auto' }}>
              <button
                className="btn btn--primary btn--sm"
                onClick={() => setViewing(viewing === report.id ? null : report.id)}
              >
                {viewing === report.id ? 'Close' : 'View Report'}
              </button>
              <button
                className="btn btn--secondary btn--sm"
                onClick={() => downloadBlob(buildPDFText(report), `${report.title}.txt`, 'text/plain')}
              >
                <Download size={12} /> PDF
              </button>
              <button
                className="btn btn--ghost btn--sm"
                onClick={() => downloadBlob(buildCSV(report), `${report.title}.csv`, 'text/csv')}
              >
                <Download size={12} /> Excel
              </button>
            </div>

            {/* Inline Report Viewer */}
            {viewing === report.id && (
              <div style={{
                marginTop: 4, borderTop: '1px solid var(--color-border-muted)', paddingTop: 16,
                animation: 'fadeIn 0.2s ease',
              }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <BarChart2 size={14} style={{ color: 'var(--color-primary)' }} />
                    <span style={{ fontSize: 13, fontWeight: 700, color: 'var(--color-text-primary)' }}>Full Report</span>
                  </div>
                  <button className="icon-btn" style={{ width: 24, height: 24 }} onClick={() => setViewing(null)}><X size={14} /></button>
                </div>
                {(FULL_CONTENT[report.id]?.sections ?? [{ title: 'Summary', body: report.preview }]).map((s) => (
                  <div key={s.title} style={{ marginBottom: 14 }}>
                    <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--color-text-muted)', marginBottom: 5 }}>{s.title}</div>
                    <div style={{ fontSize: 13, color: 'var(--color-text-secondary)', lineHeight: 1.65 }}>{s.body}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}

        {/* Generate new report card */}
        <div
          className="card"
          style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, minHeight: 220, border: '2px dashed var(--color-border-muted)', background: 'transparent', cursor: 'pointer' }}
          onClick={handleGenerate}
        >
          <div style={{ width: 48, height: 48, background: 'var(--color-primary-light)', borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Plus size={22} style={{ color: 'var(--color-primary)' }} />
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 4 }}>Generate New Report</div>
            <div style={{ fontSize: 12, color: 'var(--color-text-muted)' }}>AI creates an executive narrative from your latest data</div>
          </div>
          <button className="btn btn--primary btn--sm" disabled={generating}>
            {generating ? 'Generating…' : 'Start'}
          </button>
        </div>
      </div>

      <style>{`
        @keyframes fadeIn { from { opacity: 0; transform: translateY(-6px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  )
}
